default: &default
  adapter: postgresql
  encoding: unicode
  host: <%= ENV['POSTGRES_HOST'] or "localhost" %>
  username: <%= ENV['POSTGRES_USER'] or "kerank" %>
  password: <%= ENV['POSTGRES_PASSWORD'] or "" %>
  pool: 5

development:
  <<: *default
  database: rencontredejeunesse_development

test:
  <<: *default
  database: rencontredejeunesse_test

production:
  <<: *default
  database: rencontredejeunesse_production
  username: rencontredejeunesse
  password:
